groupbuddies/council

app/assets/javascripts/app/components/comment_form/templates/comment_form.html.slim
app/assets/javascripts/app/components/on_scroll/on_scroll.js
app/assets/javascripts/app/discussions/show.html.slim
app/assets/stylesheets/components/_base.css.sass
app/assets/stylesheets/components/_editor.css.sass
app/assets/stylesheets/components/_reset.css.sass
app/assets/stylesheets/components/_sliding_screen.css.sass
app/assets/stylesheets/components/_toolbar.css.sass
app/assets/stylesheets/components/_top_bar_layout.css.sass

Also fixes small layout issues on the comment form.
There is no carrot color for now, there is no right way to do it, although there are hacks, we can explore them later.

Adds Editor component

---

vendor/assets/javascripts/angular-material.js
vendor/assets/stylesheets/angular-material.css
vendor/assets/stylesheets/default-theme.css

This is necessary in order to use $mdThemingProvider

Updated angular-material to 0.7.0-rc1

---

app/assets/javascripts/app/components/discussion_card/discussion_card.js
app/assets/javascripts/app/components/discussion_card/templates/discussion_card.html.slim
app/assets/javascripts/app/discussions/discussions.js
app/assets/javascripts/app/discussions/index.html.slim

I'm moving this into an encapsulated space because we are going to need a directive that will adapt to different states

Encapsulates discussion card login to a directive

---

config/autoprefixer.yml

Updates flex box rules, now the Council works on iPhone

Fix flex box rules

---

app/assets/javascripts/app/discussions/templates/form.html.slim
app/assets/stylesheets/components/_theme.css.scss
app/views/devise/sessions/new.slim

- Updates angular material to lastest version;
- Removes custom angular mateiral build;
- Adds angular material to bower;
- Changes md-text-float to md-input-container;

Changes md-text-float to md-input-container

---

app/assets/javascripts/app/core/models/discussion.js
app/assets/javascripts/app/discussions/discussion.js

Allows discussions/show to render while a request is made to the backend,
updating the interface once it's finished. In the future it wil probably need
a loading indication somewhere.

Allows discussions/show to render faster

---

app/assets/javascripts/app/components/comments_list/comments_list.js
app/assets/javascripts/app/components/comments_list/templates/comments_list.html.slim
app/assets/javascripts/app/discussions/index.html.slim
app/assets/javascripts/app/discussions/show.html.slim
app/assets/stylesheets/components/_comment.css.sass
app/assets/stylesheets/components/_detailed_discussion.css.sass
app/assets/stylesheets/components/_discussion.css.sass
app/assets/stylesheets/components/_discussion_list.css.sass
app/assets/stylesheets/components/_theme.css.scss
app/assets/stylesheets/utilities/_margin.css.sass
app/views/devise/sessions/new.slim
app/views/pages/index.html.slim

The objective is to correct spacing and line-heights on the mobile version. No desktop concerns here

Corrects line-heights and spacing through the app

---

app/assets/javascripts/app/components/comment_form/comment_form.js
app/assets/javascripts/app/components/comment_form/templates/comment_form.html.slim
app/assets/javascripts/app/components/comments_list/comments_list.js
app/assets/javascripts/app/components/comments_list/templates/comments_list.html.slim
app/assets/javascripts/app/discussions/discussion.js
app/assets/javascripts/app/discussions/discussions.module.js
app/assets/javascripts/app/discussions/show.html.slim

Open comment for edition on the comment form.

Update comment on the comment form

---

app/assets/javascripts/app/core/device.js
app/assets/javascripts/app/discussions/discussion_form.js
app/assets/javascripts/app/discussions/discussions.module.js
app/assets/javascripts/app/discussions/templates/desktop.html.slim
app/assets/javascripts/app/discussions/templates/discussion.html.slim
app/assets/javascripts/app/discussions/templates/edit_header_desktop.html.slim
app/assets/javascripts/app/discussions/templates/header_desktop.html.slim
app/assets/javascripts/application.js
bower.json

When on desktop, the create and edit discussion form is shown in one page instead.

Desktop layout for create and edit discussion

---

app/assets/stylesheets/components/_theme.css.scss

Fix toolbar on mobile

---

app/assets/stylesheets/components/_page.css.sass
app/assets/stylesheets/components/_top_bar_layout.css.sass

[Fix this bug](https://trello.com/c/QaGvjM7k/82-white-border-on-bottom-of-the-pages)

Corrects white stripe on bottom of the page

---

app/assets/javascripts/app/discussions/discussion_form.js
app/assets/javascripts/app/discussions/templates/desktop.html.slim
app/assets/javascripts/app/discussions/templates/desktop_edit.html.slim
app/assets/javascripts/app/discussions/templates/mobile_edit_step2.html.slim
app/assets/javascripts/app/discussions/templates/mobile_step2.html.slim

[Fix this bug](https://trello.com/c/Asl4O8lv/72-if-i-click-three-times-on-the-button-to-submit-a-new-discussion-it-creates-three-discussions)

Can only submit new discussion once

---

app/assets/javascripts/app/discussions/templates/desktop.html.slim
app/assets/javascripts/app/discussions/templates/desktop_edit.html.slim
app/assets/stylesheets/components/_editor.css.sass

Fixes discussion new/edit form

---

Capfile
Gemfile
Gemfile.lock
Procfile.production
config/database.yml
config/deploy.rb
config/deploy/production.rb
config/nginx.conf
config/puma.rb
puppet/gb-council.yaml
puppet/install-app
puppet/manifest.pp

Already online at http://new.council.groupbuddies.com
This follows the standard process I've used for the blog and for our own 
website.
All 3 apps will now be served by the Obi Wan machine.

Sets up deploy to our own machine

---

app/assets/javascripts/app/core/notifications.js

Push notifications service

---

app/assets/javascripts/app/components/button/button.js
app/assets/javascripts/app/components/button/templates/raised.html.slim
app/assets/javascripts/app/components/comment_form/controller.js
app/assets/javascripts/app/components/comment_form/templates/desktop.html.slim
app/assets/javascripts/app/components/comment_form/templates/mobile.html.slim
app/assets/javascripts/app/discussions/show.html.slim

The create comment button needs to be disabled during the sever request in
order to prevent someone from creating the the same comment multiple times.

Fix to double click for new comment

---

app/views/notifications_mailer/_email_view_action.erb
app/views/notifications_mailer/new_comment.slim
app/views/notifications_mailer/new_discussion.slim

Fixes https://github.com/groupbuddies/council/issues/114

Adds Email view actions. Fixes #114

---

app/models/user.rb
spec/models/user_spec.rb

Fixes https://github.com/groupbuddies/council/issues/129

Shows full name on users

---

app/assets/stylesheets/components/_discussion_list.css.sass

Fixes comment-count-spacing

---

app/assets/javascripts/app/discussions/index/index.html.slim
app/assets/stylesheets/components/_icons.css.sass

Fixes cursor on menu icon

---

app/assets/javascripts/app/components/comments_list/templates/comments_list.html.slim
app/assets/javascripts/app/discussions/show/show.html.slim
app/assets/stylesheets/components/_base.css.sass
app/assets/stylesheets/components/_button_link.css.sass
app/assets/stylesheets/components/_comment.css.sass

Adds button link style

---

app/assets/javascripts/app/discussions/index/index.html.slim
app/assets/stylesheets/components/_base.css.sass
app/assets/stylesheets/components/_icons.css.sass
app/assets/stylesheets/components/_toolbar.css.sass

Center Council logo

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/material-overrides.scss

Fix for issue https://github.com/groupbuddies/council/issues/141

Changes input colors.

---

app/models/subscription.rb
spec/models/subscription_spec.rb

Fixes issue https://github.com/groupbuddies/council/issues/118

Stops notifications for new users

---

Gemfile.lock
app/assets/javascripts/app/components/on_scroll/on_scroll.js
app/assets/javascripts/application.js
bower.json

Removes unused 'fastclick' module.
Fixes require of 'ng-fastclick' in application.js

Fixes bower.json file.

---

app/assets/javascripts/app/app.js
app/assets/javascripts/app/components/page/page.js
app/assets/javascripts/app/components/page/templates/page.html.slim
app/assets/javascripts/app/discussions/index/index.html.slim
app/assets/javascripts/app/discussions/new/templates/desktop.html.slim
app/assets/javascripts/app/discussions/new/templates/desktop_edit.html.slim
app/assets/javascripts/app/discussions/new/templates/discussion.html.slim
app/assets/javascripts/app/discussions/show/show.html.slim
app/assets/javascripts/application.js
app/assets/stylesheets/components/_page.css.sass
app/assets/stylesheets/components/_top_bar_layout.css.sass
bower.json

Adds Angular Elastic module to make textarea in new discussion form elastic.
Also adds page directive and fixes discussion views' layouts and style.
This fixes issue https://github.com/groupbuddies/council/issues/135.

Elastic text area in discussion form

---

app/assets/javascripts/app/discussions/new/templates/desktop.html.slim
app/assets/javascripts/app/discussions/new/templates/desktop_edit.html.slim
app/assets/javascripts/app/discussions/new/templates/mobile_edit_step1.html.slim
app/assets/javascripts/app/discussions/new/templates/mobile_edit_step2.html.slim
app/assets/javascripts/app/discussions/new/templates/mobile_step1.html.slim
app/assets/javascripts/app/discussions/new/templates/mobile_step2.html.slim

The discussion forms were broken in mobile.

Fixes discussion mobile views

---

app/assets/javascripts/app/components/comments_list/templates/comments_list.html.slim
app/assets/javascripts/app/components/discussion_card/discussion_card.js
app/assets/javascripts/app/components/discussion_card/templates/discussion_card.html.slim
app/assets/javascripts/app/core/models/user.js
app/assets/javascripts/app/discussions/discussions.module.js
app/assets/javascripts/app/discussions/index/discussions.js
app/assets/javascripts/app/discussions/index/index.html.slim
app/assets/stylesheets/components/_card_list.css.sass
app/assets/stylesheets/components/_discussion.css.sass
app/assets/stylesheets/components/_page.css.sass
app/controllers/users_controller.rb
app/models/user.rb
app/serializers/discussion_serializer.rb
app/serializers/user_serializer.rb
config/routes.rb
spec/controllers/users_controller_spec.rb
spec/models/user_spec.rb

This adds a discussion's participants to discussion cards.
The discussion's author will be displayed to the right of the card and the other participants will be to the left of the card.

Add participants to discussion card.
